version: '3.9'

services:

  postgres:
    image: postgres:16-alpine
    ports:
        - 5432:5432
    volumes:
          - ~/apps/postgres:/var/lib/postgresql/data
          - ./SQL/setup:/docker-entrypoint-initdb.d
    environment:
          - POSTGRES_PASSWORD=${PG_PW}
          - POSTGRES_USER=${PG_USER}
          - POSTGRES_DB=${PG_DB}
    restart: always